[tool.poetry]
name = "handlers"
version = "0.1.0"
description = "Schema preview docker image dependencies"
authors = ["Amazon Web Services"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = ">=3.7.1,<3.11"

aenum = "2.2.6"
aiohttp = "3.8.1"
asn1crypto = "1.5.1"
awslambdaric = "2.0.1"
awswrangler = "2.20.1"
backoff = "1.11.1"
beautifulsoup4 = "4.10.0"
boto3 = "1.26.107"
botocore = "1.29.107"
cachetools = "5.0.0"
certifi = "2021.10.8"
charset-normalizer = "2.0.12"
decorator = "5.1.1"
distlib = "0.3.4"
edx-codejail = "3.2.0"
et-xmlfile = "1.1.0"
filelock = "3.6.0"
google-api-core = "2.7.1"
google-api-python-client = "2.43.0"
google-auth = "2.6.2"
google-auth-httplib2 = "0.1.0"
google-cloud-bigquery = "2.34.3"
google-cloud-bigquery-storage = "2.13.1"
google-cloud-core = "2.2.3"
google-cloud-storage = "2.2.1"
google-crc32c = "1.3.0"
google-resumable-media = "2.3.2"
googleapis-common-protos = "1.56.0"
gremlinpython = "3.5.2"
grpcio = "1.44.0"
grpcio-status = "1.44.0"
httplib2 = "0.20.4"
idna = "3.3"
importlib-metadata = "2.1.3"
isodate = "0.6.1"
jmespath = "1.0.0"
jsonpath-ng = "1.5.3"
lxml = "4.9.1"
nest-asyncio = "1.5.5"
numpy = "1.21.5"
openpyxl = "3.0.9"
opensearch-py = "1.1.0"
pandas = "1.3.5"
pg8000 = "1.24.1"
platformdirs = "2.5.1"
ply = "3.11"
progressbar2 = "4.2.0"
proto-plus = "1.20.3"
protobuf = "3.20.2"
pyarrow = "7.0.0"
pyasn1 = "0.4.8"
pyasn1-modules = "0.2.8"
PyMySQL = "1.0.2"
pynt = "0.8.2"
pyparsing = "^3.0.9" # was "3.0.7"
python-utils = "3.1.0"
rdflib = "6.1.1"
regex = "2022.3.15"
requests = "2.27.1"
requests-aws4auth = "1.1.2"
rsa = "4.8"
s3transfer = "0.6.0"
scramp = "1.4.1"
simplejson = "^3.17.2" # was "3.17.6" but "depends on awslambdaric (2.0.1) which depends on simplejson (3.17.2)"
six = "1.16.0"
soupsieve = "2.3.2"
typing-extensions = "4.1.1"
uritemplate = "4.1.1"
urllib3 = "1.26.9"
virtualenv = "20.14.0"
yarl = "1.7.2"
db-dtypes = "1.0.1"

####################################################
# Optional - packages that should only be loaded in docker build
# To support local dependencies in connectors, we need to split out these deps
# Make sure to add these to extra `ada-docker-image` group
####################################################
redshift-connector = {version="2.0.905", optional=true}
SPARQLWrapper = {version="1.8.5", optional=true}
pytz = {version=">=2020.1,<2021.9", optional=true} # was "2022.1" but "redshift-connector (2.0.905) which depends on pytz (>=2020.1,<2021.9)"
pymongo = "^4.3.3"
oracledb = "^1.3.0"

[tool.pytest.ini_options]
pythonpath = [
  "."
]

[tool.poetry.dev-dependencies]
pytest = "^7.0.1"
pytest-cov = "^3.0.0"
pytest-only = "^2.0.0"
moto = "^4.1.0"
assertpy = "^1.1"
pytest-mock = "^3.10.0"
mongomock = "4.1.2"
requests-mock = "1.10.0"

[tool.poetry.extras]
ada-docker-image = ["redshift-connector", "SPARQLWrapper", "pytz"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
