[tool.poetry]
name = "script-validation"
version = "0.1.0"
description = "Customer-provided script validation"
authors = ["Amazon Web Services"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.9"
bandit = "^1.7.4"
shortuuid = "^1.0.9"

[tool.poetry.dev-dependencies]
pytest = "^7.0.1"
pytest-cov = "^3.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
