/*! Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
SPDX-License-Identifier: Apache-2.0 */
////////////////////////////////////////////////////////////////
// REGISTER CONNECTOR INFRA - DO NOT EDIT THIS FILE
////////////////////////////////////////////////////////////////
import { ConnectorIntegrator } from './static';
import { Connectors } from '@ada/connectors/interface';
import { ID } from '../index';
import DynamicStack from './dynamic/stack';

declare module '@ada/connectors/interface' {
  interface CONNECTOR_INFRA_REGISTRY {
    [ID]: Connectors.IConnectorInfra<{}, {}, {}>
  }
}

Connectors.Infra.register(ID, {
  staticIntegrator: ConnectorIntegrator,
  dynamicStackClass: DynamicStack,
});
